(function(){function d(b){try{return!!(b&&b.IsValid&&b.IsValid())}catch(c){return!1}}function y(b){for(var c=null;d(b);){try{c=b.GetParent()}catch(e){c=null}if(!d(c))return b;b=c}return null}function r(b,c){try{if(!d(b)||!b.FindChildrenWithClassTraverse)return null;var e=b.FindChildrenWithClassTraverse(c)||[];return e.length&&d(e[0])?e[0]:null}catch(f){return null}}function z(b){try{if(d(b)&&typeof b.text==="string")return b.text}catch(c){}try{if(d(b)&&b.GetAttributeString)return b.GetAttributeString("text",
"")}catch(c){}return""}function H(b){if(!d(b))return-1;var c="";try{c=b.style&&typeof b.style.clip==="string"?b.style.clip:""}catch(I){}try{!c&&b.GetAttributeString&&(c=b.GetAttributeString("style",""))}catch(I){}b=c.lastIndexOf("deg");var e=c.lastIndexOf(",",b);if(b<0||e<0)return-1;for(e+=1;e<b&&c.charCodeAt(e)<=32;)e+=1;var f=1;c.charCodeAt(e)===45?(f=-1,e+=1):c.charCodeAt(e)===43&&(e+=1);for(var g=0,h=0,k=0,m=!1;e<b;e+=1){var n=c.charCodeAt(e);if(n>=48&&n<=57)m=!0,k===0?g=g*10+n-48:(h+=(n-48)/
k,k*=10);else if(n===46&&k===0)k=10;else if(n>32)return-1}return m?f*(g+h):-1}function p(b,c){try{return!!(d(b)&&b.BHasClass&&b.BHasClass(c))}catch(e){return!1}}function t(){d(a.magnum.ammoLabel)&&(a.magnum.ammoLabel.SetHasClass("MagnumAmmoGlow",a.magnum.active),a.magnum.ammoLabel.SetHasClass("SplitShotAmmoGlow",a.split.active),a.magnum.ammoLabel.SetHasClass("BloodTributeAmmoGlow",a.blood.active))}function u(b){if(d(b.notifier)){if(b.active){var c=0;a.magnum.active&&a.magnum.activationOrder>b.activationOrder&&
(c+=1);a.split.active&&a.split.activationOrder>b.activationOrder&&(c+=1);a.blood.active&&a.blood.activationOrder>b.activationOrder&&(c+=1)}else c=0;b.notifier.SetHasClass("NotifierOneOffset",b.active&&c===1);b.notifier.SetHasClass("NotifierTwoOffsets",b.active&&c===2)}}function q(){u(a.magnum);u(a.split);u(a.blood)}function A(){d(a.magnum.notifier)&&(a.magnum.notifier.SetHasClass("MagnumBuffActive",a.magnum.active),a.magnum.notifier.style.visibility=a.magnum.active?"visible":"collapse",a.magnum.notifier.style.opacity=
a.magnum.active?"1":"0");t()}function B(){d(a.split.notifier)&&(a.split.notifier.SetHasClass("SplitShotActive",a.split.active),a.split.notifier.style.visibility=a.split.active?"visible":"collapse",a.split.notifier.style.opacity=a.split.active?"1":"0")}function C(){d(a.blood.notifier)&&(a.blood.notifier.SetHasClass("BloodTributeActive",a.blood.active),a.blood.notifier.style.visibility=a.blood.active?"visible":"collapse",a.blood.notifier.style.opacity=a.blood.active?"1":"0")}function v(b){b=!!b;a.magnum.active!==
b&&(a.magnum.active=b,a.magnum.activationOrder=b?a.nextActivationOrder++:0,A(),q())}function w(b){b=!!b;a.split.active!==b&&(a.split.active=b,a.split.activationOrder=b?a.nextActivationOrder++:0,B(),t(),q())}function D(b){b=!!b;a.blood.active!==b&&(a.blood.active=b,a.blood.activationOrder=b?a.nextActivationOrder++:0,C(),t(),q())}function E(){a.magnum.seen=!1;a.magnum.cooldownMask=null;a.magnum.cooldownLabel=null;a.magnum.coolingDown=!1;a.magnum.reloading=!1;a.magnum.cooldown=-1;a.magnum.cooldownDegrees=
-1;a.magnum.readySamples=0;v(!1)}function F(){a.split.seen=!1;a.split.ready=!1;a.split.activeUntil=0;w(!1)}function G(b,c,e,f){if(d(c.item)&&p(c.item,"trained"))return c.item;c.item=null;if(b<c.nextScanAt)return null;c.nextScanAt=b+.5;d(a.root)||(a.root=y(l));if(!d(a.root))return null;b=null;try{b=a.root.FindChildTraverse(e)}catch(g){}if(!d(b)||!p(b,"trained"))return null;c.item=b;f();return b}function J(){if(!d(a.blood.abilityContainer)){a.blood.abilityContainer=null;for(var b=0;b<a.blood.slots.length;b+=
1)a.blood.slots[b]=null,a.blood.labels[b]=null;d(a.root)||(a.root=y(l));if(!d(a.root))return!1;try{a.blood.abilityContainer=a.root.FindChildTraverse("abilitiesContainer")}catch(c){}if(!d(a.blood.abilityContainer))return!1}for(b=0;b<a.blood.slots.length;b+=1){if(!d(a.blood.slots[b])){a.blood.labels[b]=null;try{a.blood.slots[b]=a.blood.abilityContainer.FindChildTraverse(K[b])}catch(c){a.blood.slots[b]=null}}d(a.blood.slots[b])&&!d(a.blood.labels[b])&&(a.blood.labels[b]=r(a.blood.slots[b],"ability_name"))}return!0}
function L(b){if(b<a.blood.nextScanAt)return d(a.blood.togglePanel)?a.blood.togglePanel:null;a.blood.nextScanAt=b+.5;a.blood.togglePanel=null;if(!J())return null;for(b=0;b<a.blood.slots.length;b+=1){var c=a.blood.slots[b];if(d(c)&&z(a.blood.labels[b])==="BLOOD TRIBUTE")return a.blood.togglePanel=c}return null}function x(){if(d(l)){var b=Date.now()/1E3,c=!1,e=!1,f=!1;if(!d(a.magnum.notifier)){try{a.magnum.notifier=l.FindChildTraverse("MercurialMagnumNotifier")}catch(m){a.magnum.notifier=null}c=!0}if(!d(a.split.notifier)){try{a.split.notifier=
l.FindChildTraverse("SplitShotNotifier")}catch(m){a.split.notifier=null}e=!0}if(!d(a.blood.notifier)){try{a.blood.notifier=l.FindChildTraverse("BloodTributeNotifier")}catch(m){a.blood.notifier=null}f=!0}d(a.magnum.ammoLabel)||(a.magnum.ammoLabel=r(l,"weapon_ammo"),c=!0);c&&A();e&&B();f&&C();(c||e||f)&&q();c=G(b,a.split,"upgrade_split_shot",F);d(c)?(c=p(c,"cooling_down"),a.split.seen?(c||(a.split.ready=!0),c&&a.split.ready?(a.split.ready=!1,a.split.activeUntil=b+5,w(!0)):a.split.active&&b>=a.split.activeUntil&&
w(!1)):(a.split.seen=!0,a.split.ready=!c),c=!0):((a.split.seen||a.split.active)&&F(),c=!1);e=c;c=L(b);d(c)?(D(p(c,"toggled_on")),c=!0):(D(!1),c=!1);f=c;c=G(b,a.magnum,"upgrade_ethereal_bullets",E);if(d(c)){d(a.magnum.cooldownLabel)||(a.magnum.cooldownLabel=r(c,"cooldown_timer"));b=p(c,"cooling_down");e=z(a.magnum.cooldownLabel);f=0;for(var g=!1,h=0;h<e.length;h+=1){var k=e.charCodeAt(h);if(k>=48&&k<=57)f=f*10+k-48,g=!0;else if(g)break}e=g?f:-1;if(!d(a.magnum.cooldownMask))try{a.magnum.cooldownMask=
c.FindChildTraverse("cooldown_mask")}catch(m){a.magnum.cooldownMask=null}c=H(a.magnum.cooldownMask);f=p(l,"reloading");a.magnum.seen?(g=(h=c>=0&&a.magnum.cooldownDegrees>=0)&&c>a.magnum.cooldownDegrees+.5,h=!h&&e>=0&&a.magnum.cooldown>=0&&e>a.magnum.cooldown+1,g=b&&a.magnum.coolingDown&&(g||h),h=f&&!a.magnum.reloading,b&&!a.magnum.coolingDown&&a.magnum.readySamples>=2||g?(v(!0),a.magnum.readySamples=0):a.magnum.active&&h&&v(!1),b||(a.magnum.readySamples+=1),a.magnum.coolingDown=b,a.magnum.reloading=
f,a.magnum.cooldown=e,a.magnum.cooldownDegrees=c):(a.magnum.seen=!0,a.magnum.coolingDown=b,a.magnum.reloading=f,a.magnum.cooldown=e,a.magnum.cooldownDegrees=c,a.magnum.readySamples=b?0:1);$.Schedule(.05,x)}else(a.magnum.seen||a.magnum.active)&&E(),$.Schedule(e||f?.05:.5,x)}}var K=["abilityButton0","abilityButton1","abilityButton2","abilityButton3"],l=$.GetContextPanel(),a={root:null,nextActivationOrder:1,magnum:{item:null,nextScanAt:0,notifier:null,cooldownMask:null,cooldownLabel:null,ammoLabel:null,
active:!1,activationOrder:0,seen:!1,coolingDown:!1,reloading:!1,cooldown:-1,cooldownDegrees:-1,readySamples:0},split:{item:null,nextScanAt:0,notifier:null,seen:!1,ready:!1,active:!1,activationOrder:0,activeUntil:0},blood:{togglePanel:null,nextScanAt:0,abilityContainer:null,slots:[null,null,null,null],labels:[null,null,null,null],notifier:null,active:!1,activationOrder:0}};x()})();
