(()=>{function e(a){try{return!!a&&(!a.IsValid||a.IsValid())}catch(b){return!1}}function K(a){try{return e(a)&&a.GetParent?a.GetParent():null}catch(b){return null}}function f(a,b){try{if(!e(a)||!b)return null;if(a.FindChildTraverse)return a.FindChildTraverse(b);if(a.FindChild)return a.FindChild(b)}catch(c){}return null}function L(a,b){var c;for(c=0;b&&c<b.length;c+=1){var d=f(a,b[c]);if(e(d))return d}return null}function z(a,b){try{return e(a)&&a.FindChildrenWithClassTraverse?a.FindChildrenWithClassTraverse(b)||
[]:[]}catch(c){return[]}}function n(a,b){try{return e(a)&&a.BHasClass&&a.BHasClass(b)}catch(c){return!1}}function m(a,b){try{e(a)&&b&&a.AddClass&&!n(a,b)&&a.AddClass(b)}catch(c){}}function h(a,b){try{e(a)&&b&&a.RemoveClass&&n(a,b)&&a.RemoveClass(b)}catch(c){}}function r(a,b){try{e(a)&&(b=b==null?"":String(b),a.text!==b&&(a.text=b))}catch(c){}}function D(a,b){try{e(a)&&(a.visible=!!b,a.style.visibility=b?"visible":"collapse")}catch(c){}}function A(a){try{if(!e(a))return"";if(a.GetAttributeString)return String(a.GetAttributeString("class",
""));if(a.className)return String(a.className)}catch(b){}return""}function p(a,b){return n(a,b)||A(a).indexOf(b)!==-1}function x(a,b){var c;for(c=0;c<b.length;c+=1)if(p(a,b[c]))return!0;return!1}function M(a){e(a.objectiveMarkerRoot)||(a.objectiveMarkerRoot=L(a.root,N));return a.objectiveMarkerRoot}function ha(a,b){if(!e(a)||!b)return!1;if(n(a,b)||A(a).indexOf(b)!==-1)return!0;try{var c=a.Children?a.Children():[]}catch(d){c=[]}for(a=0;c&&a<c.length;a+=1)if(n(c[a],b)||A(c[a]).indexOf(b)!==-1)return!0;
return!1}function O(a,b){var c;for(c=0;c<b.length;c+=1)if(ha(a,b[c]))return!0;return!1}function ia(a){if(a===void 0||a===null)return 0;a=String(a).replace(/,/g,"").trim().toLowerCase();var b=a.match(/^([0-9]*\.?[0-9]+)\s*([kmb])?$/);if(!b)return 0;a=parseFloat(b[1]);if(isNaN(a))return 0;b=b[2]||"";b==="k"?a*=1E3:b==="m"?a*=1E6:b==="b"&&(a*=1E9);return Math.round(a)}function E(a){if(!a)return 0;var b=String(a).match(/(\d+):(\d{1,2})/);if(!b)return 0;a=parseInt(b[1],10)||0;b=parseInt(b[2],10)||0;b>
59&&(b%=60);return a*60+b}function v(a){a=Math.max(0,a|0);var b=a/60|0;a%=60;return(b<10?"0"+b:""+b)+":"+(a<10?"0"+a:""+a)}function P(a,b){var c=ja();if(c!==null)return c;c=Date.now?Date.now():0;if(!b&&e(a.gameTimePanel)&&c-a.lastGameTimeLookup<800)return E(a.gameTimePanel.text);a.lastGameTimeLookup=c;for(b=0;b<Q.length;b+=1)if(c=f(a.root,Q[b]),e(c)&&c.text)return a.gameTimePanel=c,E(c.text);c=z(a.root,"GameTime");a.gameTimePanel=c&&c.length?c[0]:null;return e(a.gameTimePanel)?E(a.gameTimePanel.text):
0}function R(a){return typeof a!=="number"||isNaN(a)?null:a|0}function F(a,b){if(!a||typeof a[b]!=="function")return null;a=a[b]();return typeof a!=="number"||isNaN(a)?null:a|0}function ja(){try{if(typeof Game!=="undefined"){var a=F(Game,"GetDOTATime");if(a!==null)return a;a=F(Game,"GetGameTime");if(a!==null)return a;a=R(Game.Time);if(a!==null)return a;a=R(Game.GameTime);if(a!==null)return a}if(typeof GameUI!=="undefined"&&(a=F(GameUI,"GetGameTime"),a!==null))return a}catch(b){}return null}function ka(a){var b;
try{if(typeof Game!=="undefined"&&Game.GetMapInfo){var c=(b=Game.GetMapInfo())?b.map_display_name:"";if(c==="hero_testing_hideout"||c==="hideout"||c==="dl_hideout")return!0}}catch(d){}b=f(a,"Hud");return n(a,"connectedToHideout")||n(a,"connectedtoHideout")||n(a,"connectedtohideout")||n(a,"InHideout")||n(a,"inHideoutIntro")||n(b,"connectedToHideout")||n(b,"connectedtoHideout")||n(b,"connectedtohideout")||n(b,"InHideout")}function la(a){return n(a,"gamemode_streetbrawl")||n(f(a,"Hud"),"gamemode_streetbrawl")}
function S(a){return e(a)?(a=z(a,"ScoreLabel"))&&a.length?ia(a[0].text):0:0}function ma(a,b){var c=S(a.teamScoreFriendly);var d=S(a.teamScoreEnemy);var g=Math.max(c,d),l=Math.min(c,d),k=0,q="--",u="neutral",w="TopbarRankAdvantageNeutral";g>0&&(k=(g-l)/g*100*(c>=d?1:-1),q=(k>0?"+":"")+k.toFixed(1)+"%",b=b/60<15?15:10,k<=-b?(u="bad",w="TopbarRankAdvantageBad"):k>=b&&(u="good",w="TopbarRankAdvantageGood"));r(a.urnTrackerLabel,q);e(a.advantageLabel)&&r(a.advantageLabel,q);h(a.urnTracker,"good");h(a.urnTracker,
"bad");h(a.urnTracker,"neutral");q=a.urnNetworthCard;h(q,"good");h(q,"bad");h(q,"neutral");m(q,u);u=a.advantage;h(u,"TopbarRankAdvantageGood");h(u,"TopbarRankAdvantageBad");h(u,"TopbarRankAdvantageNeutral");m(u,w);D(a.urnTracker,!0);D(a.urnNetworthCard,!0);D(a.urnHudCard,!0);return{diffPct:k||0,friendly:c,enemy:d}}function na(a){a=M(a);var b;if(!e(a))return{panel:null,warning:!1,present:!1};a=z(a,"capture_point");for(b=0;a&&b<a.length;b+=1){var c=a[b];if(e(c)&&p(c,"capture_point")){if(p(c,"koth_warning"))return{panel:c,
warning:!0,present:!0};if(p(c,"active")&&x(c,["team_neutral","team_1","team_2","team1","team2"]))return{panel:c,warning:!1,present:!0}}}return{panel:null,warning:!1,present:!1}}function B(a){return a<=805?745:745+(Math.floor((a-805)/420)+1)*420}function oa(a){var b=a.kothTeam1,c=a.kothTeam2;e(b)||(a.kothTeam1=b=f(a.root,"KothCashInMeterTeam1"));e(c)||(a.kothTeam2=c=f(a.root,"KothCashInMeterTeam2"));if(p(b,"capturing")){if(p(b,"friendly"))return"friendly";if(p(b,"enemy"))return"enemy"}if(p(c,"capturing")){if(p(c,
"friendly"))return"friendly";if(p(c,"enemy"))return"enemy"}return p(a.kothCashInMeter,"friendly")?"friendly":p(a.kothCashInMeter,"enemy")?"enemy":""}function G(a,b){return x(a.kothCashInMeter,b)||x(a.root,b)}function pa(a,b,c){var d=na(a);e(a.kothCashInMeter)||(a.kothCashInMeter=f(a.root,"KothCashInMeter"));var g=G(a,"koth_enabled in_range capturing contested captured give_up_warning gave_up".split(" "));var l=G(a,["capturing","contested","give_up_warning"]);var k=G(a,["captured","gave_up","captured_neutral"]);
if(d.warning)a.riftWarningStartedAt||(a.riftWarningStartedAt=b),b=Math.max(0,25-(b-a.riftWarningStartedAt)),c=b>0?"Rift "+v(b):"Rift spawn",b="TopbarRankObjectiveRiftWarning",a.riftObservedLive=!0;else if(a.riftWarningStartedAt=0,l)l=oa(a),c=c&&typeof c.diffPct==="number"?c.diffPct:0,g=12,b="TopbarRankObjectiveRiftNeutral",l==="enemy"?c=-c:l!=="friendly"&&(c=0),l=Math.abs(c)/15,l=l<0?0:l>1?1:l,c<0?(g=12+-6*l,b="TopbarRankObjectiveRiftGood"):c>0&&(g=12+6*l,b="TopbarRankObjectiveRiftBad"),c="Cap "+
Math.round(g)+"s",a.riftObservedLive=!0;else if(g||d.present)c=k?"Rift done":"Rift live",b="TopbarRankObjectiveRiftLive",a.riftObservedLive=!0;else{a.riftObservedLive&&(c=a.riftSpawnAccumulator||B(b),b>c+60&&(c=B(b)),a.riftSpawnAccumulator=c+420,a.riftObservedLive=!1);k=M(a);var q;g=!1;l=p(a.root,"PlayerIsHoldingIdol");c=!1;if(e(k))for(k=z(k,"map_button"),q=0;k&&q<k.length;q+=1)if(d=k[q],e(d)&&x(d,"idol_spawn old_spawn idol_return_snippet idol_return idol_return_friendly idol_return_enemy idol_dropping".split(" "))){g=
!0;l=l||p(d,"holding_idol");c=p(d,"idol_dropping");x(d,["idol_return","idol_return_friendly","idol_return_enemy","idol_return_snippet"]);break}b<600?(k=600-b,d=!1):(k=(b-600)%300,k=d=k===0?0:300-k,d=d<=1);l?(a.urnHeldSeenAt||(a.urnHeldSeenAt=b),b-=a.urnHeldSeenAt,b>=90?(c="Urn empty",b="TopbarRankObjectiveUrnDecay"):b>=45?(c="Urn decay",b="TopbarRankObjectiveUrnDecay"):(c="Urn held",b="TopbarRankObjectiveUrnHeld")):(a.urnHeldSeenAt=0,g?(a.urnLiveSeenAt||(a.urnLiveSeenAt=b),b-=a.urnLiveSeenAt,c?(c=
"Urn drop",b="TopbarRankObjectiveUrnDrop"):(c=b>=180?"Urn walk":"Urn live",b="TopbarRankObjectiveUrnLive")):(a.urnLiveSeenAt=0,g=a.riftSpawnAccumulator||B(b),b>g+60&&(g=B(b)),a.riftSpawnAccumulator=g,c=Math.max(0,g-60-b),b=Math.max(0,g+60-b),d||k<=c?(c=d?"Urn now":"Urn "+v(k),b=k<=30?"TopbarRankObjectiveUrnSoon":"TopbarRankObjectiveIdle"):(c="Rift "+v(c)+"-"+v(b),b="TopbarRankObjectiveRiftLive")))}c!==a.lastObjectiveText&&(a.lastObjectiveText=c,r(a.urnHud,c));b!==a.lastObjectiveClass&&(a.lastObjectiveClass=
b,a=a.urnHudCard,h(a,"TopbarRankObjectiveIdle"),h(a,"TopbarRankObjectiveRiftWarning"),h(a,"TopbarRankObjectiveRiftLive"),h(a,"TopbarRankObjectiveRiftGood"),h(a,"TopbarRankObjectiveRiftNeutral"),h(a,"TopbarRankObjectiveRiftBad"),h(a,"TopbarRankObjectiveUrnSoon"),h(a,"TopbarRankObjectiveUrnLive"),h(a,"TopbarRankObjectiveUrnHeld"),h(a,"TopbarRankObjectiveUrnDrop"),h(a,"TopbarRankObjectiveUrnDecay"),m(a,b))}function T(a,b){h(a,"red");h(a,"yellow");b<10&&b%2===1?m(a,"red"):b<20&&b%2===1&&m(a,"yellow")}
function qa(a,b){h(a.buffHud,"buffWarningRed");h(a.buffHud,"buffWarningYellow");b<10&&b%2===1?m(a.buffHud,"buffWarningRed"):b<20&&b%2===1&&m(a.buffHud,"buffWarningYellow")}function H(a){a=[a.rejuvImage,a.rejuvHudImage];var b;for(b=0;b<a.length;b+=1)h(a[b],"rotating"),h(a[b],"buff"),h(a[b],"reverse"),h(a[b],"white")}function U(a,b){H(a);b.indexOf("Cd")!==-1?(m(a.rejuvImage,"reverse"),m(a.rejuvHudImage,"reverse"),m(a.rejuvImage,"rotating"),m(a.rejuvHudImage,"rotating"),y(a,.8,function(){h(a.rejuvImage,
"rotating");h(a.rejuvHudImage,"rotating")})):b.indexOf("Buff")!==-1&&(m(a.rejuvImage,"buff"),m(a.rejuvHudImage,"buff"),m(a.rejuvImage,"rotating"),m(a.rejuvHudImage,"rotating"),y(a,.8,function(){h(a.rejuvImage,"rotating");h(a.rejuvHudImage,"rotating")}))}function I(a,b,c){r(a.rejuvTime,b);r(a.rejuvHudTime,b);r(a.rejuvNum,c);r(a.rejuvHudNum,c)}function V(a){a.rejuvenatorCharges=f(a.root,"RejuvenatorCharges");a.rejuvenatorFriendly=f(a.root,"RejuvenatorFriendly");a.rejuvenatorEnemy=f(a.root,"RejuvenatorEnemy")}
function ra(a){e(a.rejuvenatorFriendly)&&e(a.rejuvenatorEnemy)||V(a);return O(a.rejuvenatorFriendly,W)||O(a.rejuvenatorEnemy,W)}function X(a){if(a.buffEndAt)a.buffEndAt=0,h(a.rejuvBuff,"TopbarRankRejuvBuffVisible"),y(a,.5,function(){try{e(a.rejuvBuff)&&!a.buffEndAt&&(a.rejuvBuff.style.opacity="0")}catch(b){}});else{h(a.rejuvBuff,"TopbarRankRejuvBuffVisible");try{e(a.rejuvBuff)&&(a.rejuvBuff.style.opacity="0")}catch(b){}}}function Y(a,b){var c;a:{var d=b||0;var g=0;if(d<=2){var l=c=0;d=t[0].duration}else{for(c=
0;c<t.length;c+=1){var k=t[c].duration;if(d<g+k){l=g;d=g+k-d;break a}g+=k}c=t.length-1;k=t[c].duration;g=(d-g)%300%k;l=d-g;d=k-g}}a.phaseIndex=c;a.phaseStart=l;a.spawnWaiting=d<=0;a.claimCount=0;a.lastChargeActive=!1;a.buffEndAt=0;a.lastSeconds=b||0;I(a,d<=0?"Spawn":v(d),t[c].label);H(a);d<=0?(m(a.rejuvImage,"white"),m(a.rejuvHudImage,"white")):U(a,t[c].name);X(a)}function Z(a){I(a,"Spawn",t[a.phaseIndex].label);H(a);m(a.rejuvImage,"white");m(a.rejuvHudImage,"white")}function aa(a,b,c){a.buffEndAt&&
(b=Math.max(0,a.buffEndAt-b),r(a.rejuvBuffTime,v(b)),(b<=0||!c)&&X(a))}function sa(a,b,c){if(a.spawnWaiting){if(Z(a),aa(a,b,c),c&&!a.lastChargeActive){a.claimCount+=1;a.buffEndAt=b+180;r(a.rejuvBuffTime,v(180));m(a.rejuvBuff,"TopbarRankRejuvBuffVisible");try{e(a.rejuvBuff)&&(a.rejuvBuff.style.opacity="1")}catch(g){}a.phaseIndex=Math.max(0,Math.min(a.claimCount>2?3:a.claimCount,t.length-1));a.phaseStart=b;a.spawnWaiting=!1;U(a,t[a.phaseIndex].name)}}else{var d=Math.max(0,t[a.phaseIndex].duration-(b-
a.phaseStart));d<=0?(a.spawnWaiting=!0,Z(a)):(I(a,v(d),t[a.phaseIndex].label),T(a.rejuvHud,d));aa(a,b,c)}a.lastChargeActive=c}function ba(a){if(ta(a)){var b=P(a,!1);(b+5<a.lastSeconds||a.lastSeconds>30&&b<=2)&&Y(a,b);a.lastSeconds=b;if(!ka(a.root)&&!la(a.root)){var c=300-b%300;r(a.buffTime,v(c));r(a.buffHudTime,v(c));T(a.buffHud,c);qa(a,c);c=ra(a);sa(a,b,c);c=ma(a,b);pa(a,b,c)}y(a,1,function(){ba(a)})}}function J(a){if(!a||a.context&&!e(a.context)||a.root&&!e(a.root))return!1;if(a.generationKey&&
a.context){try{var b=a.context[a.generationKey]}catch(c){return!1}if(b!==a.generation)return!1}return!0}function ta(a){return J(a)&&e(a.buffTime)&&e(a.rejuvTime)&&e(a.urnTrackerLabel)}function ua(a){return J(a)&&e(a.display)&&e(a.modsContainer)}function ca(a){try{$.Schedule(.5,function(){e(a)&&da()})}catch(b){}}function y(a,b,c){var d=a?a.generation:null;try{$.Schedule(b,function(){a&&a.generation!==d||(!a||J(a))&&c()})}catch(g){}}function va(a){var b=[0,0,0,0],c=0;if(!e(a))return{spent:0,signature:"0:0:0:0"};
for(a=[a];a.length;){var d=a.pop();if(e(d)){var g,l=d,k=b,q=A(l),u=0;for(g=0;g<ea.length;g+=1){var w=ea[g];if(n(l,w)||q.indexOf(w)!==-1)k[g]+=1,u+=wa[w]||0}c+=u;try{var C=d.Children?d.Children():[]}catch(xa){C=[]}for(d=0;C&&d<C.length;d+=1)a.push(C[d])}}return{spent:c,signature:b[0]+":"+b[1]+":"+b[2]+":"+b[3]}}function fa(a){if(ua(a)){var b=va(a.modsContainer);b.signature!==a.lastSpentSignature&&(a.lastSpentSignature=b.signature,b=(b.spent/1E3).toFixed(1)+"k",b!==a.lastSpentText&&(a.lastSpentText=
b,r(a.display,b)));y(a,.5,function(){fa(a)})}}function da(){try{var a=$&&$.GetContextPanel?$.GetContextPanel():null}catch(g){a=null}if(e(a))if(f(a,"BuffTime")&&f(a,"RejuvTime")&&f(a,"UrnTrackerLabel")){var b=a;var c=b;var d;if(e(c))for(d=K(c);e(d);)c=d,d=K(c);else c=null;if(e(c)){try{b.__QolLiteTopbarRootGeneration=(b.__QolLiteTopbarRootGeneration||0)+1}catch(g){}b={context:b,root:c,generation:b.__QolLiteTopbarRootGeneration||1,generationKey:"__QolLiteTopbarRootGeneration",lastSeconds:0,phaseIndex:0,
phaseStart:0,spawnWaiting:!1,claimCount:0,lastChargeActive:!1,buffEndAt:0,lastGameTimeLookup:0,gameTimePanel:null,buffTime:f(c,"BuffTime"),buffHudTime:f(c,"BuffTimeHUD"),buffHud:f(c,"BuffHUD"),rejuvTime:f(c,"RejuvTime"),rejuvHudTime:f(c,"RejuvTimeHUD"),rejuvNum:f(c,"RejuvNum"),rejuvHudNum:f(c,"RejuvNumHUD"),rejuvImage:f(c,"RejuvImg"),rejuvHudImage:f(c,"RejuvImgHUD"),rejuvHud:f(c,"RejuvHUD"),rejuvBuff:f(c,"RejuvBuff"),rejuvBuffTime:f(c,"RejuvTimeBuff"),urnHud:f(c,"UrnHUD"),urnTracker:f(c,"UrnTracker"),
urnTrackerLabel:f(c,"UrnTrackerLabel"),urnNetworthCard:f(c,"UrnNetworthCard"),urnHudCard:f(c,"UrnHudCard"),teamScoreFriendly:f(c,"TeamScoreFriendly"),teamScoreEnemy:f(c,"TeamScoreEnemy"),advantage:f(c,"TopbarRankAdvantage"),advantageLabel:f(c,"TopbarRankAdvantageLabel"),rejuvenatorCharges:null,rejuvenatorFriendly:null,rejuvenatorEnemy:null,kothCashInMeter:f(c,"KothCashInMeter"),kothTeam1:f(c,"KothCashInMeterTeam1"),kothTeam2:f(c,"KothCashInMeterTeam2"),objectiveMarkerRoot:L(c,N),riftWarningStartedAt:0,
riftSpawnAccumulator:0,riftObservedLive:!1,urnLiveSeenAt:0,urnHeldSeenAt:0,lastObjectiveText:"",lastObjectiveClass:""};V(b)}else b=null;b&&e(b.buffTime)&&e(b.rejuvTime)&&e(b.urnTrackerLabel)?(c=P(b,!0),Y(b,c),ba(b),b=!0):b=!1;b||ca(a)}else if(f(a,"SpentSoulDisplay")&&f(a,"PlayerModsContainer")){b=a;try{b.__QolLiteTopbarPlayerGeneration=(b.__QolLiteTopbarPlayerGeneration||0)+1}catch(g){}b={context:b,root:b,generation:b.__QolLiteTopbarPlayerGeneration||1,generationKey:"__QolLiteTopbarPlayerGeneration",
display:f(b,"SpentSoulDisplay"),modsContainer:f(b,"PlayerModsContainer"),lastSpentSignature:"",lastSpentText:""};e(b.display)&&e(b.modsContainer)?(fa(b),b=!0):b=!1;b||ca(a)}}var N=["HudMinimap","hud_minimap","HudMinimapContainer","minimap_container","ObjectivesMap"],Q=["HudGameTime","GameTime","MainGameTime"],W=["RejuvCount_1","RejuvCount_2","RejuvCount_3","RejuvCount_4"],wa={isTier1:800,isTier2:1600,isTier3:3200,isTier4:6400},ea=["isTier1","isTier2","isTier3","isTier4"],t=[{name:"initial",duration:0,
label:"1"},{name:"firstCd",duration:413,label:"2"},{name:"secondCd",duration:353,label:"3"},{name:"thirdCd",duration:293,label:"3"}];da()})();typeof AddClass!=="undefined"&&(this.AddClass=AddClass);typeof RemoveClass!=="undefined"&&(this.RemoveClass=RemoveClass);
