var w=function(){function k(a){typeof QolLiteMapLog!=="undefined"&&QolLiteMapLog.log("poi: "+a)}function e(a){var b=$.GetContextPanel();return b?b.FindChildTraverse(a):null}function t(){for(var a=e("map_render");a;){if(a.BHasClass&&a.BHasClass("is_underground"))return!0;a=a.GetParent?a.GetParent():null}return!1}function u(a){var b=QolLiteMapState.get(),d=Number(b.poiMarkerSizePx)||3;d=a.small?Math.max(1,Math.round(d*.6)):d;b=Math.max(.01,Math.min(1,Number(b.poiOpacity)||.8));var c=a.panel;c.style.width=
d+"px";c.style.height=d+"px";c.style.transform="translateX("+-d/2+"px) translateY("+-d/2+"px)";c.style.backgroundColor=x[a.t]+b.toFixed(2)+")";c.style.zIndex="10"}function f(){for(var a=QolLiteMapState.get(),b=0;b<g.length;b++){var d=g[b];g[b].panel.style.visibility=a.poiFrom3Min&&r||d.t==="crate"&&!a.poiCratesEnabled||d.t==="statue"&&!a.poiStatuesEnabled||d.small&&!a.poiShowSmall||a.poiLevelMode==="auto"&&d.under!==l?"collapse":"visible"}}function n(){for(var a=0;a<g.length;a++)u(g[a])}function v(){var a=
t();a!==l&&(l=a,k("level -> "+(a?"underground":"surface")),QolLiteMapState.get().poiLevelMode==="auto"&&f());a=(a=e("GameTime"))&&typeof a.text==="string"?(a=a.text.replace(/<[^>]+>/g,"").match(/(\d+):(\d{2})/))?parseInt(a[1],10)*60+parseInt(a[2],10):null:null;a=a!==null&&a<180;a!==r&&(r=a,k("spawnGate -> "+(a?"before 3:00 (POI hidden)":"spawned")),f());$.Schedule(.25,v)}function p(a,b,d){(a=e(a))&&a.SetPanelEvent("onactivate",function(){var c={};c[b]=!QolLiteMapState.get()[b];QolLiteMapState.patch(c);
k(b+" = "+c[b]);m();d()})}function m(){for(var a=QolLiteMapState.get(),b=[["minimap_crates_toggle",a.poiCratesEnabled],["minimap_statues_toggle",a.poiStatuesEnabled],["minimap_poi_small_toggle",a.poiShowSmall],["minimap_poi_level_toggle",a.poiLevelMode==="auto"],["minimap_poi_spawn_toggle",a.poiFrom3Min]],d=0;d<b.length;d++){var c=e(b[d][0]);c&&typeof c.SetSelected==="function"&&c.SetSelected(b[d][1])}if(b=e("minimap_crates_size_slider"))if(b=b.FindChildTraverse("Slider"))b.value=a.poiMarkerSizePx;
if(b=e("minimap_crates_opacity_slider"))if(b=b.FindChildTraverse("Slider"))b.value=a.poiOpacity}function y(){p("minimap_crates_toggle","poiCratesEnabled",f);p("minimap_statues_toggle","poiStatuesEnabled",f);p("minimap_poi_small_toggle","poiShowSmall",f);p("minimap_poi_spawn_toggle","poiFrom3Min",f);var a=e("minimap_poi_level_toggle");a&&a.SetPanelEvent("onactivate",function(){var c=QolLiteMapState.get().poiLevelMode==="auto"?"both":"auto";QolLiteMapState.patch({poiLevelMode:c});k("poiLevelMode = "+
c);m();f()});if(a=e("minimap_crates_size_slider")){var b=a.FindChildTraverse("Slider");b&&(b.min=1,b.max=8,b.SetPanelEvent("onvaluechanged",function(){QolLiteMapState.patch({poiMarkerSizePx:Math.max(1,Math.min(8,Math.round(b.value)))});n()}))}if(a=e("minimap_crates_opacity_slider")){var d=a.FindChildTraverse("Slider");d&&d.SetPanelEvent("onvaluechanged",function(){QolLiteMapState.patch({poiOpacity:Math.max(.01,Math.min(1,Math.round(d.value*100)/100))});n()})}(a=e("minimap_reset_crates_button"))&&
a.SetPanelEvent("onactivate",function(){var c=QolLiteMapState.DEFAULTS;QolLiteMapState.patch({poiCratesEnabled:c.poiCratesEnabled,poiStatuesEnabled:c.poiStatuesEnabled,poiShowSmall:c.poiShowSmall,poiLevelMode:c.poiLevelMode,poiMarkerSizePx:c.poiMarkerSizePx,poiOpacity:c.poiOpacity});m();n();f()})}var x={crate:"rgba(74, 158, 255, ",statue:"rgba(255, 207, 74, "},g=[],l=!1,r=!1;return{init:function(){l=t();var a=e("minimap_markers");if(a){for(;a.GetChildCount()>0;)a.GetChild(0).DeleteAsync(0);g=[];var b=
typeof QolLiteMapPoiData!=="undefined"?QolLiteMapPoiData.dl_midtown:null;if(b&&b.pois){for(var d=0;d<b.pois.length;d++){var c=b.pois[d];if(typeof c.u==="number"&&typeof c.v==="number"){var h=$.CreatePanel("Panel",a,"poi_"+d);h.style.horizontalAlign="left";h.style.verticalAlign="top";h.style.x=(c.u*100).toFixed(4)+"%";h.style.y=(c.v*100).toFixed(4)+"%";c={panel:h,t:c.t,small:!!c.small,under:c.z<0};u(c);g.push(c)}}f()}else k("no QolLiteMapPoiData for map dl_midtown")}else k("#minimap_markers not found, skip render");
y();m();v();if(typeof QolLiteMapLog!=="undefined"){for(h=c=d=b=a=0;h<g.length;h++){var q=g[h];q.t==="crate"?q.small?b++:a++:q.t==="statue"&&(q.small?c++:d++)}QolLiteMapLog.info("poi: "+g.length+" markers (crates "+a+"/"+b+" small, statues "+d+"/"+c+" small), underground="+l)}},refresh:function(){m();f();n()}}}();typeof w!=="undefined"&&(this.QolLiteMapPoi=w);
