var T=function(){function n(a){var b=$.GetContextPanel();return b?b.FindChildTraverse(a):null}function t(a){typeof QolLiteMapLog!=="undefined"&&QolLiteMapLog.log("urn: "+a)}function I(a){typeof QolLiteMapLog!=="undefined"&&QolLiteMapLog.info("urn: "+a)}function J(){return typeof QolLiteMapUrnData!=="undefined"&&QolLiteMapUrnData.dl_midtown?QolLiteMapUrnData.dl_midtown:null}function K(a){return p===null||u===null?null:(a-u)%2===0?p:p==="left"?"right":"left"}function U(){var a=n("GameTime");if(!a||
typeof a.text!=="string")return null;a=a.text.replace(/<[^>]+>/g,"");var b=a.match(/(\d+):(\d{2}):(\d{2})/);return b?parseInt(b[1],10)*3600+parseInt(b[2],10)*60+parseInt(b[3],10):(a=a.match(/(\d+):(\d{2})/))?parseInt(a[1],10)*60+parseInt(a[2],10):null}function L(a){for(var b=n("map_render");b;){if(b.BHasClass&&b.BHasClass(a))return!0;b=b.GetParent?b.GetParent():null}return!1}function M(a){if(!a)return!1;if(a.BHasClass&&(a.BHasClass("active")||a.BHasClass("active_map_button")))return!0;var b=a.style?
a.style.visibility:"";a=a.style?a.style.opacity:"";return!(!b||b==="collapse"||a==="0"||a==="0.0")}function B(a){return a&&a.style?(a=String(a.style.position||"").match(/^\s*([0-9.+\-]+)%/))?parseFloat(a[1])<50?"left":"right":null:null}function x(a){var b=$.GetContextPanel();if(!b||!b.FindChildrenWithClassTraverse)return null;if(a=b.FindChildrenWithClassTraverse(a))for(b=0;b<a.length;b++)if(M(a[b]))return a[b];return null}function V(a){if(a===null||!y||p===null)return null;var b=J();if(!b||!b.spawns)return null;
var c=a<600?0:Math.floor((a-600)/300)+1,f=K(c);return f?(b=(b=b.spawns[f])&&(b.mid||b.mid))?{u:b.u,v:b.v,secs:600+c*300-a,window:300,side:f}:null:null}function W(){if(h&&h.root&&h.root.IsValid&&h.root.IsValid())return h;var a=n("minimap_urn_host");if(!a)return null;a=$.CreatePanel("Panel",a,"bm_urn_marker");a.AddClass("bm_urn");a.style.horizontalAlign="left";a.style.verticalAlign="top";$.CreatePanel("Panel",a,"").AddClass("bm_urn_backer");var b=$.CreatePanel("Panel",a,"");b.AddClass("bm_urn_ring");
$.CreatePanel("Panel",a,"").AddClass("bm_urn_icon");var c=$.CreatePanel("Label",a,"");c.AddClass("bm_urn_timer");return h={root:a,ring:b,timer:c}}function C(){h&&h.root&&(h.root.style.visibility="collapse");z=!1}function D(a){a=(a<0?0:a>255?255:a).toString(16);return a.length<2?"0"+a:a}function X(){if(k&&k.root&&k.root.IsValid&&k.root.IsValid())return k;var a=n("minimap_urn_host");if(!a)return null;a=$.CreatePanel("Panel",a,"bm_urn_descent_marker");a.AddClass("bm_urn");a.style.horizontalAlign="left";
a.style.verticalAlign="top";$.CreatePanel("Panel",a,"").AddClass("bm_urn_backer");var b=$.CreatePanel("Panel",a,"");b.AddClass("bm_urn_ring");b.AddClass("bm_urn_descent_ring");$.CreatePanel("Panel",a,"").AddClass("bm_urn_icon");var c=$.CreatePanel("Label",a,"");c.AddClass("bm_urn_timer");return k={root:a,ring:b,timer:c}}function N(){k&&k.root&&(k.root.style.visibility="collapse")}function O(){var a=!!QolLiteMapState.get().urnTrackerEnabled,b=U(),c=x("idol_spawn"),f;a:{for(f=0;f<v.length;f++){var e=
x(v[f]);if(e){f=e;break a}}f=null}b!==null&&q!==null&&b+3<q&&(t("clock went backwards (t="+b+" < anchor="+q+") - reset tracking"),u=p=q=null,E=y=!1,F=null,G="",A=!0,w=r=null,C(),N());if(typeof QolLiteMapLog!=="undefined"&&QolLiteMapLog.isDebug()){if((e=$.GetContextPanel())&&e.FindChildrenWithClassTraverse){for(var d=[],l=0;l<v.length;l++){var g=e.FindChildrenWithClassTraverse(v[l]);if(g)for(var m=0;m<g.length;m++)M(g[m])&&d.push(v[l]+":"+(B(g[m])||"?"))}e=d.join(" ")}else e="";e!==G&&(G=e,t("idols["+
(b===null?"?":b)+"s]: "+(e||"(none)")));(e=x("idol_spawn")||x("idol_dropping"))&&(e=B(e))&&(F=e)}c&&A&&(c=B(c))&&(e=b!==null?Math.round((b-600)/300):u,y&&(d=K(e))&&c!==d&&I("MISPREDICT: predicted "+d+" but urn spawned "+c+" (slot "+e+") - re-anchoring side"),p=c,u=e,y=!0,A=!1,b!==null&&(q=b),r=b,w=(d=(d=(d=J())&&d.spawns&&d.spawns[c])&&d.mid)?{u:d.u,v:d.v}:null,t("anchor(spawn): side="+c+" slot="+e+" t="+q));!f&&E&&(A=!0,t("resolve lastLiveSide="+F));if((E=f)||!a)C();else if(c=V(b))if(e=L("gDetailView")||
L("gScoreboardOpen"),d=W()){d.root.style.x=(c.u*100).toFixed(3)+"%";d.root.style.y=(c.v*100).toFixed(3)+"%";d.root.style.visibility="visible";l=1-Math.max(0,Math.min(1,c.secs/(c.window||300)));if(d.ring)try{d.ring.style.clip="radial(50% 50%, 0deg, "+Math.round(l*360)+"deg)"}catch(P){}d.timer&&(l=d.timer,g=c.secs,g===null?g="--:--":(g<0&&(g=0),m=g%60,g=Math.floor(g/60)+":"+(m<10?"0"+m:m)),l.text=g,d.timer.style.visibility=e?"visible":"collapse");z||(z=!0,t("marker shown: u="+c.u.toFixed(3)+" v="+c.v.toFixed(3)+
" next="+c.side+" in="+Math.round(c.secs)+"s"))}else z||I("show FAILED: minimap_urn_host / marker missing");else C();if(a&&f&&r!==null&&b!==null&&b-r>=0&&b-r<12){if(a=b-r,(b=X())&&w){b.root.style.x=(w.u*100).toFixed(3)+"%";b.root.style.y=(w.v*100).toFixed(3)+"%";b.root.style.visibility="visible";f=Math.max(0,Math.min(1,a/12));if(b.ring){try{var Y=b.ring.style;c=f;c<0&&(c=0);c>1&&(c=1);if(c<.5){var Q=255;var R=Math.round(77+c/.5*133);var S=77}else c=(c-.5)/.5,Q=Math.round(255+-178*c),R=Math.round(210+
14*c),S=Math.round(77+45*c);var Z="#"+D(Q)+D(R)+D(S);Y.washColor=Z}catch(P){}try{b.ring.style.clip="radial(50% 50%, 0deg, "+Math.round(f*360)+"deg)"}catch(P){}}b.timer&&(b.timer.text=String(Math.max(0,Math.ceil(12-a))),b.timer.style.visibility="visible")}}else N();$.Schedule(.15,O)}function H(){var a=n("minimap_urn_tracker_toggle");a&&typeof a.SetSelected==="function"&&a.SetSelected(!!QolLiteMapState.get().urnTrackerEnabled)}function aa(){var a=n("minimap_urn_tracker_toggle");a&&a.SetPanelEvent("onactivate",
function(){QolLiteMapState.patch({urnTrackerEnabled:!QolLiteMapState.get().urnTrackerEnabled});H()})}var h=null,z=!1,q=null,p=null,u=null,y=!1,E=!1,F=null,G="",A=!0,k=null,r=null,w=null,v=["idol_spawn","idol_dropping","idol_return","idol_return_friendly","idol_return_enemy"];return{init:function(){aa();H();O()},refresh:function(){H()}}}();typeof T!=="undefined"&&(this.QolLiteMapUrn=T);
