// Bundled from BetterMap (gfkm) - do not edit here: change upstream and re-bundle.
// Upstream: github.com/gfkm/BetterMap @ a7b55cf, mod/panorama/scripts/urn_data.js
// Renamed for QOL Lite: Bettermap* -> QolLiteMap*, BettermapUmm -> QolLiteMapUmmAdapter,
// POI_DATA/URN_DATA -> QolLiteMapPoiData/QolLiteMapUrnData. "[BetterMap]" log prefix, UMM id
// "bettermap" and bm_/Bm class names are upstream names kept on purpose. Doc paths in the
// comments below (docs/..., hud.vcss, hud_minimap.vcss) refer to the upstream repository.
"use strict";

// GENERATED by pipeline/extract_poi.py - do not edit by hand.
// Source: dl_midtown default_ents (item_crate_spawn objective positions).
var QolLiteMapUrnData = {
    dl_midtown: {
        spawns: {
            left:  { mid: { u: 0.19382, v: 0.5 }, top: { u: 0.28869, v: 0.38095 }, bottom: { u: 0.32887, v: 0.64286 } },
            right: { mid: { u: 0.79315, v: 0.50446 }, top: { u: 0.76488, v: 0.4256 }, bottom: { u: 0.6994, v: 0.625 } }
        }
    }
};
