(()=>{var r={umm:1,t:"register",id:"enhanced_quickbuy",name:"Enhanced Quickbuy",settings:[{id:"enabled",type:"toggle",label:"Enabled",default:!0,description:"Enable all Enhanced Quickbuy features."},{type:"group",label:"Display"},{id:"show_hud_items",type:"toggle",label:"Show queued items on HUD",default:!0,description:"Show Enhanced Quickbuy information during normal gameplay."},{id:"preview_count",type:"slider",label:"Items shown",min:1,max:5,step:1,default:3,description:"Number of queued items shown on the HUD, including the next item."},
{type:"group",label:"Shop"},{id:"show_queue_costs",type:"toggle",label:"Queue costs in shop",default:!0,description:"Show the cumulative cost beside each queued item in the shop."},{id:"show_shop_total",type:"toggle",label:"Total queue cost in shop",default:!0,description:"Show the total cost of the quickbuy queue in the shop."}]},h={enabled:!0,show_hud_items:!0,preview_count:3,show_queue_costs:!0,show_shop_total:!0},D=[{rootId:"QuickbuyUpcomingPreview2",entryPanelId:"QuickbuyPreview2Entry",soulsLabelId:"QuickbuyUpcomingPreview2SoulsNeededLabel",
queueIndex:1},{rootId:"QuickbuyUpcomingPreview3",entryPanelId:"QuickbuyPreview3Entry",soulsLabelId:"QuickbuyUpcomingPreview3SoulsNeededLabel",queueIndex:2},{rootId:"QuickbuyUpcomingPreview4",entryPanelId:"QuickbuyPreview4Entry",soulsLabelId:"QuickbuyUpcomingPreview4SoulsNeededLabel",queueIndex:3},{rootId:"QuickbuyUpcomingPreview5",entryPanelId:"QuickbuyPreview5Entry",soulsLabelId:"QuickbuyUpcomingPreview5SoulsNeededLabel",queueIndex:4}],t={"basic magazine":"extended magazine","dispel magic":"debuff remover",
"mystic reach":"mystic expansion","mystic regen":"mystic regeneration","improved cooldown":"compress cooldown","sharp shooter":"sharpshooter","spellslinger headshots":"spirit rend"},u={"compress cooldown":"s2r://panorama/images/items/spirit/improved_cooldown_psd.vtex","mystic expansion":"s2r://panorama/images/items/spirit/mystic_reach_psd.vtex","mystic regeneration":"s2r://panorama/images/items/spirit/mystic_regen_psd.vtex","debuff reducer":"s2r://panorama/images/items/vitality/debuff_reducer_psd.vtex",
"debuff remover":"s2r://panorama/images/items/vitality/debuff_remover_psd.vtex","dispel magic":"s2r://panorama/images/items/vitality/debuff_remover_psd.vtex"},v={"Alchemical Seal":["Mystic Reach"],"Arcane Surge":["Extra Stamina"],"Arctic Blast":["Cold Front"],"Armor Piercing Rounds":["High Velocity Rounds"],"Boundless Spirit":["Improved Spirit"],"Burst Fire":["Rapid Rounds"],Capacitor:["Tesla Bullets"],Colossus:["Extra Health"],"Crippling Headshot":["Weakening Headshot"],"Crushing Fists":["Melee Charge"],
"Cultist Sacrifice":["Monster Rounds"],"Disarming Hex":["Rusted Barrel"],"Divine Barrier":["Guardian Ward"],"Enduring Speed":["Sprint Boots"],"Escalating Exposure":["Mystic Vulnerability"],"Escalating Resilience":["Basic Magazine"],"Express Shot":["High Velocity Rounds"],"Focus Lens":["Spirit Sap"],Fortitude:["Extra Health"],"Fury Trance":["Bullet Lifesteal"],"Greater Expansion":["Mystic Reach"],"Guardian Ward":["Grit"],Headhunter:["Headshot Booster"],"Healing Booster":["Extra Regen"],"Healing Nova":["Healing Rite"],
"Healing Tempo":["Healing Booster"],"Improved Spirit":["Extra Spirit"],Indomitable:["Reactive Barrier"],Infuser:["Spirit Lifesteal"],Juggernaut:["Enduring Speed"],"Kinetic Dash":["Extra Stamina"],Leech:["Bullet Lifesteal","Spirit Lifesteal"],Lifestrike:["Melee Lifesteal"],"Lightning Scroll":["Mystic Slow"],"Mercurial Magnum":["Quicksilver Reload"],"Opening Rounds":["High Velocity Rounds"],"Point Blank":["Close Quarters"],"Radiant Regeneration":["Mystic Regen"],"Rapid Recharge":["Extra Charge"],"Reactive Barrier":["Grit"],
"Rescue Beam":["Healing Rite"],"Sharp Shooter":["High Velocity Rounds","Long Range"],Spellbreaker:["Debuff Reducer"],"Spellslinger Headshots":["Spirit Shredder Bullets"],"Spirit Shielding":["Grit"],"Spirit Snatch":["Spirit Strike"],"Spiritual Overflow":["Spirit Lifesteal"],"Stamina Mastery":["Extra Stamina"],"Superior Cooldown":["Improved Cooldown"],"Superior Duration":["Duration Extender"],"Surge of Power":["Extra Spirit"],"Swift Striker":["Rapid Rounds"],Tankbuster:["Mystic Burst"],"Titanic Magazine":["Basic Magazine"],
"Transcendent Cooldown":["Superior Cooldown"],"Trophy Collector":["Sprint Boots"],Unstoppable:["Debuff Reducer"],"Vampiric Burst":["Bullet Lifesteal"],"Veil Walker":["Sprint Boots"],"Vortex Web":["Slowing Hex"],"Weapon Shielding":["Grit"],"Weighted Shots":["Slowing Bullets"]},E="hasAbility isWeapon isArmor isTech isTier0 isTier5 HideModTierLabel isEnhanced hasUpgradeLevel Locked unowned owned newSlotUnlocked IsNewItem".split(" "),F=["OnCooldown","VerticalCooldown"],G=["ModTierLevel1","ModTierLevel2",
"ModTierLevel3","ModTierLevel4","ModTierLevel5"],l=a=>a===null||typeof a==="undefined"?"":a.toString(),w=a=>l(a).replace(/\s+/g," ").replace(/^\s+|\s+$/g,""),m=a=>{a=w(a).toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").replace(/^\s+|\s+$/g,"");return Object.prototype.hasOwnProperty.call(t,a)?t[a]:a},p=a=>{a=l(a).match(/\d+/g);if(!a||a.length===0)return 0;a=parseInt(a.join(""),10);return isFinite(a)?a:0},f=(a,b)=>a&&a.FindChildTraverse?a.FindChildTraverse(b):null,k=(a,b,c)=>{a&&a.SetHasClass&&
a.SetHasClass(b,!!c)},n=(a,b)=>(a=f(a,b))?a.text:"",H=a=>{if(!a||!a.GetChildCount||!a.GetChild)return[];var b=[];for(let c=0;c<a.GetChildCount();c++)b.push(a.GetChild(c));return b},q=(a,b,c)=>{if(!a)return c;a.BHasClass&&a.BHasClass(b)&&c.push(a);H(a).forEach(d=>{q(d,b,c)});return c},I=a=>{var b=w(n(a,"ModName"));return{itemPanel:a,itemName:b,itemKey:m(b),baseSoulsCost:p(n(a,"ModCost")),effectiveSoulsCost:0,cumulativeSoulsCost:0,remainingSoulsCost:0}},J=a=>({itemPanel:a,sellSoulsCredit:Math.floor(p(n(a,
"ModCost"))/2)}),K=a=>a.reduce((b,c)=>b+c.sellSoulsCredit,0),L=(()=>Object.keys(v).reduce((a,b)=>{var c=m(b);a[c]=v[b].map(m);return a},{}))(),M=a=>{var b={};a.forEach((c,d)=>{c.effectiveSoulsCost=c.baseSoulsCost;c.cumulativeSoulsCost=0;c.remainingSoulsCost=0;c.itemKey&&(b[c.itemKey]||(b[c.itemKey]=[]),b[c.itemKey].push({queueIndex:d,soulsCost:c.baseSoulsCost,isConsumed:!1}))});return b},N=(a,b)=>a?a.find(c=>!c.isConsumed&&c.queueIndex<b)||null:null,O=(a,b)=>{a.forEach((c,d)=>{var e=L[c.itemKey];
e&&e.forEach(g=>{if(g=N(b[g],d))g.isConsumed=!0,c.effectiveSoulsCost-=g.soulsCost})})},P=(a,b)=>{var c=0;a.forEach(d=>{var e=d.effectiveSoulsCost;d.effectiveSoulsCost=e<0?0:e;c+=d.effectiveSoulsCost;d.cumulativeSoulsCost=c;e=c-b;d.remainingSoulsCost=e<0?0:e});return c},Q=a=>{a.forEach(b=>{if(b.itemPanel){k(b.itemPanel,"HasRemainingSoulsNeeded",h.enabled&&h.show_queue_costs&&b.remainingSoulsCost>0);var c=String(b.cumulativeSoulsCost);if(b=f(b.itemPanel,"QueueRemainingSoulsLabel"))b.text=l(c)}})},x=
(a,b,c)=>{a&&c.forEach(d=>{var e=!!(b&&b.BHasClass&&b.BHasClass(d));k(a,d,e)})},R=a=>(a=f(a,"ModIconImage"))&&a.GetAttributeString?a.GetAttributeString("src",""):"",S=(a,b)=>{var c=m(a);if(Object.prototype.hasOwnProperty.call(u,c))return u[c];a="weapon";b&&b.BHasClass&&(b.BHasClass("isArmor")?a="vitality":b.BHasClass("isTech")&&(a="spirit"));return(b=c.replace(/\s+/g,"_"))?`s2r://panorama/images/items/${a}/${b}_psd.vtex`:""},y=(a,b,c)=>{if(a){F.forEach(e=>{k(a,e,!1)});x(a,b,E);var d=f(a,"ModIconImage");
c=R(b)||S(c,b);d&&d.SetImage&&d.SetImage(c||"");x(f(a,"mod_tier_label"),f(b,"mod_tier_label"),G)}},T=a=>{var b=$.GetContextPanel();b&&D.forEach(c=>{var d=f(b,c.rootId),e=f(b,c.entryPanelId);e=f(e,"ModIcon");var g=f(b,c.soulsLabelId);d&&(k(d,"HasPreviewItem",!1),k(d,"CanAffordUpcoming",!1),g&&(g.text=l("0")),y(e,null,""),c=c.queueIndex<h.preview_count?a[c.queueIndex]:null,h.enabled&&c&&c.itemPanel&&(g&&(g.text=l(String(c.remainingSoulsCost))),y(e,f(c.itemPanel,"ModIcon"),c.itemName),k(d,"HasPreviewItem",
!0),k(d,"CanAffordUpcoming",c.remainingSoulsCost<=0)))})},z=a=>{var b=h.enabled,c=b&&h.show_hud_items,d=f(a,"QuickbuyNextSoulsNeeded"),e=f(a,"QuickbuyUpcomingPreviewContainer");a=f(a,"QuickbuyShopTotalSummary");d&&k(d,"EnhancedQuickbuyHidden",!c);e&&k(e,"EnhancedQuickbuyHidden",!c||h.preview_count<=1);a&&k(a,"EnhancedQuickbuyHidden",!b||!h.show_shop_total)},A=(a,b)=>{Object.prototype.hasOwnProperty.call(h,a)&&(h[a]=a==="preview_count"?Math.max(1,Math.min(5,Math.round(Number(b)||1))):!!b,(a=$.GetContextPanel())&&
z(a))},B=()=>{$.DispatchEvent("ClientUI_FireOutput",JSON.stringify(r))};$.RegisterForUnhandledEvent("ClientUI_FireOutput",a=>{if(typeof a==="string"&&a.indexOf('"umm"')!==-1){try{var b=JSON.parse(a)}catch(c){return}b&&b.umm===1&&(b.t==="hello"?B():b.t==="set"&&b.id===r.id&&A(b.key,b.value))}});var C=()=>{var a=$.GetContextPanel();if(a){var b=f(a,"QuickbuyShopTotalCostLabel");z(a);var c=f(a,"QuickbuyQueue");c=q(c,"QuickbuyItem",[]).map(I);var d=f(a,"QuickbuySellQueue");d=q(d,"QuickbuyItem",[]).map(J);
var e;a:{for(e=$.GetContextPanel();e;){var g=f(e,"CurrentGoldAmount");if(g){e=g;break a}if(!e.GetParent)break;e=e.GetParent()}e=null}e=e?p(n(e,"hudCurGoldLabel")):0;d=K(d);e+=d;g=M(c);O(c,g);d=P(c,e)-d;d=d<0?0:d;b&&(b.text=l(String(d)));if(a=f(a,"QuickbuyNextSoulsNeededLabel"))a.text=l(String(c.length===0?0:c[0].remainingSoulsCost));Q(c);T(c)}$.Schedule(.1,C)};Object.keys(h).forEach(a=>{A(a,h[a])});B();$.Schedule(0,C)})();
