var p=function(){function k(){for(var a=QolLiteMapState.get(),c=[],b={},f=0;f<h.length;f++){var d=h[f],e={id:d.id,type:d.type,label:d.label};d.type==="slider"?(e.min=d.min,e.max=d.max,e.step=d.step,e.unit=d.unit):d.type==="select"&&(e.options=d.options);var g=d;var l=a;g=g.get?g.get(l):l[g.key];e["default"]=g;c.push(e);b[d.id]=g}a={umm:1,t:"register",id:"bettermap",name:"BetterMap",settings:c,values:b};try{$.DispatchEvent("ClientUI_FireOutput",JSON.stringify(a))}catch(r){}}function m(){n||(n=!0,typeof QolLiteMapLog!==
"undefined"&&QolLiteMapLog.info("umm: core present - deferring settings UI to UMM"),typeof QolLiteMapSettings!=="undefined"&&QolLiteMapSettings.setUmmActive&&QolLiteMapSettings.setUmmActive(!0))}function q(a){if(typeof a==="string"&&a.indexOf('"umm"')!==-1){try{var c=JSON.parse(a)}catch(d){return}if(c&&c.umm===1)if(c.t==="hello")m(),k();else if(c.t==="set"&&c.id==="bettermap"){m();a=c.key;c=c.value;var b;a:{for(b=0;b<h.length;b++)if(h[b].id===a){b=h[b];break a}b=null}if(b){if(b.set)b=b.set(c);else{var f=
{};f[b.key]=c;b=f}QolLiteMapState.patch(b);typeof QolLiteMapPoi!=="undefined"&&QolLiteMapPoi.refresh&&QolLiteMapPoi.refresh();typeof QolLiteMapSize!=="undefined"&&QolLiteMapSize.apply&&QolLiteMapSize.apply();typeof QolLiteMapSize!=="undefined"&&QolLiteMapSize.applyClampWidth&&QolLiteMapSize.applyClampWidth();typeof QolLiteMapPosition!=="undefined"&&QolLiteMapPosition.apply&&QolLiteMapPosition.apply();typeof QolLiteMapSettings!=="undefined"&&QolLiteMapSettings.applyMapOpacity&&QolLiteMapSettings.applyMapOpacity();
typeof QolLiteMapMinimal!=="undefined"&&QolLiteMapMinimal.refresh&&QolLiteMapMinimal.refresh();typeof QolLiteMapUrn!=="undefined"&&QolLiteMapUrn.refresh&&QolLiteMapUrn.refresh();typeof QolLiteMapLog!=="undefined"&&QolLiteMapLog.log("umm: set "+a+" = "+c)}}}}var h=[{id:"poiCratesEnabled",type:"toggle",label:"Show Crates",key:"poiCratesEnabled"},{id:"poiStatuesEnabled",type:"toggle",label:"Show Golden Statues",key:"poiStatuesEnabled"},{id:"poiShowSmall",type:"toggle",label:"Show Small Objects",key:"poiShowSmall"},
{id:"poiFrom3Min",type:"toggle",label:"Objects From 3:00",key:"poiFrom3Min"},{id:"poiLevelAuto",type:"toggle",label:"Auto Level (Underground)",get:function(a){return a.poiLevelMode==="auto"},set:function(a){return{poiLevelMode:a?"auto":"both"}}},{id:"poiMarkerSizePx",type:"slider",label:"Marker Size",min:1,max:8,step:1,unit:"px",key:"poiMarkerSizePx"},{id:"poiOpacityPct",type:"slider",label:"Marker Opacity",min:10,max:100,step:5,unit:"%",get:function(a){return Math.round((Number(a.poiOpacity)||.8)*
100)},set:function(a){return{poiOpacity:Math.max(.01,Math.min(1,a/100))}}},{id:"minimapSizePx",type:"slider",label:"Minimap Size",min:200,max:800,step:20,unit:"px",key:"minimapSizePx"},{id:"mapOpacityPct",type:"slider",label:"Map Opacity",min:10,max:100,step:5,unit:"%",get:function(a){return Math.round((Number(a.mapOpacity)||.95)*100)},set:function(a){return{mapOpacity:Math.max(.01,Math.min(1,a/100))}}},{id:"minimalMapOpacityPct",type:"slider",label:"Minimalist Map Opacity",min:0,max:100,step:5,unit:"%",
get:function(a){a=Number(a.minimalMapOpacity);return Math.round((isNaN(a)?.9:Math.max(0,Math.min(1,a)))*100)},set:function(a){return{minimalMapOpacity:Math.max(0,Math.min(1,Number(a)/100))}}},{id:"minimapCorner",type:"select",label:"Minimap Corner",key:"minimapCorner",options:[{value:"bottom-right",label:"Bottom-Right"},{value:"bottom-left",label:"Bottom-Left"},{value:"top-right",label:"Top-Right"},{value:"top-left",label:"Top-Left"}]},{id:"minimapOffsetXPct",type:"slider",label:"Minimap Offset X",
min:0,max:100,step:5,unit:"%",get:function(a){return Math.round((Number(a.minimapOffsetX)||0)*100)},set:function(a){return{minimapOffsetX:Math.max(0,Math.min(1,a/100))}}},{id:"minimapOffsetYPct",type:"slider",label:"Minimap Offset Y",min:0,max:100,step:5,unit:"%",get:function(a){return Math.round((Number(a.minimapOffsetY)||0)*100)},set:function(a){return{minimapOffsetY:Math.max(0,Math.min(1,a/100))}}},{id:"hudFullWidth",type:"toggle",label:"Full-Width HUD",key:"hudFullWidth"},{id:"minimalMap",type:"toggle",
label:"Minimalist Minimap",key:"minimalMap"},{id:"ultLargeMapEnabled",type:"toggle",label:"Larger Map When Targeting",key:"ultLargeMapEnabled"},{id:"urnTrackerEnabled",type:"toggle",label:"Urn Spawn Tracker",key:"urnTrackerEnabled"}],n=!1;return{init:function(){try{$.RegisterForUnhandledEvent("ClientUI_FireOutput",q)}catch(a){}k()}}}();typeof p!=="undefined"&&(this.QolLiteMapUmmAdapter=p);
