(function(){function u(a,b,c){var d=c===void 0?B:c;$.Schedule(a,function(){q&&d===B&&b(d)})}function C(){if(L&&L.IsValid())return L;for(var a=$.GetContextPanel();a.GetParent()!==null;)a=a.GetParent();return L=a}function U(a){return M&&M.IsValid()?M:M=a.FindChildTraverse("RecentPurchasesContainer")}function V(a,b){for(;a;){if(a.BHasClass(b))return!0;a=a.GetParent()}return!1}function N(a){return a&&a.IsValid()?(a=a.FindChildrenWithClassTraverse("recentModPurchaseName"))&&a.length>0&&a[0].IsValid()?
a[0].text.trim():"":""}function W(a){return a&&a.IsValid()?(a=a.FindChildrenWithClassTraverse("recentTimePurchased"))&&a.length>0&&a[0].IsValid()?a[0].text.trim():"":""}function ra(a){return a&&a.IsValid()?(a=a.FindChildrenWithClassTraverse("recentModPurchaserHero"))&&a.length>0&&a[0].IsValid()?a[0].text.trim():"":""}function sa(a){if(!X&&(a=a.FindChildTraverse("RecentPurchasesPanel"))){var b=$.CreatePanel("ToggleButton",a,"FiltersCollapseToggle");b.AddClass("PurchaseFilterToggle");b.checked=!0;$.CreatePanel("Label",
b,"").text="Show Filters";var c=$.CreatePanel("Panel",a,"PurchaseFiltersContainer"),d=!0;$.RegisterEventHandler("Activated",b,function(){(d=!d)?c.RemoveClass("filterButtonHidden"):c.AddClass("filterButtonHidden")});b={};for(var f=0;f<v.length;f++){var g=v[f],e=c;g.group&&(b[g.group]||(b[g.group]=$.CreatePanel("Panel",c,"FilterGroup_"+g.group),b[g.group].AddClass("PurchaseFilterGroup")),e=b[g.group]);var h=$.CreatePanel("ToggleButton",e,g.id);h.AddClass("PurchaseFilterToggle");h.checked=g.active;$.CreatePanel("Label",
h,"").text=g.label;(function(k){$.RegisterEventHandler("Activated",h,function(){k.active=!k.active})})(g)}b=a.FindChild("RecentPurchases");f=a.FindChild("RecentPurchasesContainer");b&&b.SetParent(a);f&&f.SetParent(a);X=!0}}function ha(a,b){if(a&&a.IsValid()){b||=a.FindChildrenWithClassTraverse("recentPurchase");a={};for(var c=0;c<b.length;c++){var d=N(b[c]),f=W(b[c]);d&&f&&(a[d+"|"+f]=!0)}w=a}}function ta(a){try{if(typeof Game!=="undefined"&&Game.GetMapInfo){var b=Game.GetMapInfo().map_display_name;
if(["hero_testing_hideout","hideout","dl_hideout"].indexOf(b)!==-1)return!0}}catch(c){}return(b=a.FindChildTraverse("Hud"))&&(b.BHasClass("connectedToHideout")||b.BHasClass("InHideout"))?!0:a.BHasClass("connectedToHideout")||a.BHasClass("InHideout")}function ia(a){if((a=U(a))&&a.IsValid()){var b=a.GetChildCount();if(b>0)for(var c=0;c<b;c++)a.GetChild(c).DeleteAsync(0)}w={};O=!1;Y()}function Y(){P++;Q=!1;for(var a in t){var b=t[a];b&&b.IsValid()&&b.DeleteAsync(0)}J={};n=0;t={};p={};R={}}function ua(){if(n!==
2)return!1;for(var a in J){var b=J[a];if(!b||!b.IsValid())return!0}return!1}function va(){function a(){b===P&&(d--,d===0&&(n=2))}if(n!==1){n=1;var b=++P,c=C().FindChildrenWithClassTraverse("HeroNameHidden");if(c&&c.length!==0)for(var d=c.length,f=0;f<c.length;f++)(function(g){for(var e=g.GetParent(),h=null,k=0;e&&e.IsValid()&&k<16&&!(h=e.FindChildTraverse("HeroBadge"));)e=e.GetParent(),k++;h&&e?(h=h.heroid,typeof h!=="number"||h<=0?a():(e.SetDialogVariableInt("hero_id",h),function(l){u(.3,function(){if(b===
P&&n===1){if(g.IsValid()){var x=g.text.trim().toUpperCase();x&&(J[x]=l)}a()}})}(e,h))):a()})(c[f]);else n=0}}function wa(a){if(t[a]&&t[a].IsValid())return t[a];var b=J[a];if(!b||!b.IsValid())return n!==1&&(n=0),null;b=$.CreatePanel("Panel",b,"");b.AddClass("QuickPurchasesPanel");return t[a]=b}function Z(a){Q||(Q=!0,u(a||0,function(){try{var b=[],c;for(c in t){var d=t[c];if(d&&d.IsValid()){var f=p[c];f&&f.length!==0&&b.push({hero:c,panel:d})}}for(c=0;c<b.length;c++){d=125;var g=b[c].panel.GetParent();
g&&g.IsValid()&&g.BHasClass("UltimateUnlocked")&&(d=152);b[c].panel.style.marginTop=d+"px";b[c].baseMargin=d}if(!(b.length<2)){for(c=0;c<b.length;c++){var e=b[c],h=b[c].panel,k=C().FindChildTraverse("TopBar");g=0;for(d=h;d&&d.IsValid()&&d!==k;)g+=d.actualxoffset,d=d.GetParent();e.leftX=g;b[c].width=b[c].panel.actuallayoutwidth}for(e=0;e<b.length-1;e++)for(h=e+1;h<b.length;h++)if((R[b[h].hero]||0)>(R[b[e].hero]||0)){var l=b[e];b[e]=b[h];b[h]=l}l=[];for(c=0;c<b.length;c++)l[c]=b[c].baseMargin;for(c=
1;c<b.length;c++){var x=b[c].leftX,y=x+b[c].width;if(!(b[c].width<=0))for(e=0;e<c;e++)if(!(b[e].width<=0)){var r=b[e].leftX;if(x<r+b[e].width&&y>r){var D=l[e]+b[e].panel.contentheight*.75+0;D>l[c]&&(l[c]=D)}}}for(c=0;c<b.length;c++)b[c].panel.style.marginTop=l[c]+"px"}}finally{Q=!1}}))}function xa(a,b){var c=p[b];if(c){for(var d=[],f=0;f<c.length;f++)c[f]!==a&&d.push(c[f]);p[b]=d}a.IsValid()&&(a.AddClass("quickFading"),u(.3,function(){a.IsValid()&&a.DeleteAsync(0);Z(0)}))}function ya(a,b){var c=p[b];
if(c){for(var d=[],f=0;f<c.length;f++)c[f]!==a&&d.push(c[f]);p[b]=d}a.IsValid()&&a.DeleteAsync(0);Z(0)}function za(a,b){var c=ra(a).toUpperCase(),d=wa(c);if(d){p[c]||(p[c]=[]);R[c]=$.FrameTime();p[c].length>=3&&ya(p[c][0],c);d=$.CreatePanel("Panel",d,"");d.AddClass("quickPurchase");for(var f=0;f<aa.length;f++)a.BHasClass(aa[f])&&d.AddClass(aa[f]);a=$.CreatePanel("Panel",d,"");a.AddClass("quickItemInfo");if(f=QOL_LITE_PURCHASE_ICONS[b]){var g=$.CreatePanel("Panel",a,"");g.AddClass("mod_icon");(function(e,
h){u(0,function(){e.IsValid()&&(e.style.backgroundImage=h,e.style.backgroundSize="100% 100%")})})(g,f)}a=$.CreatePanel("Label",a,"");a.AddClass("quickPurchaseName");a.text=b;p[c].push(d);Z(.05);(function(e,h){u(10,function(){e.IsValid()&&xa(e,h)})})(d,c)}}function ja(a){if(q&&a===B){try{var b=C(),c=U(b);if(c&&c.IsValid()){for(var d=c.FindChildrenWithClassTraverse("recentPurchase"),f=50;f<d.length;f++)d[f].DeleteAsync(0);d.length>50&&(d.length=50);var g=d}else g=[];d=g;if(c&&c.IsValid())for(d||=c.FindChildrenWithClassTraverse("recentPurchase"),
f=0;f<d.length;f++){var e=d[f];if(e&&e.IsValid()){var h=e.FindChildrenWithClassTraverse("mod_icon");if(h&&h.length!==0){var k=h[0];if(k.IsValid()&&!k.BHasClass("iconSet")){var l=N(e);if(l){var x=QOL_LITE_PURCHASE_ICONS[l];x&&(k.style.backgroundImage=x,k.style.washColor="none",k.AddClass("iconSet"))}}}}}e={isSpectator:!1,localTeam:0};e.isSpectator=V($.GetContextPanel(),"TeamSpectator");!e.isSpectator&&c&&c.IsValid()&&(V(c,"localPlayerTeam1")?e.localTeam=1:V(c,"localPlayerTeam2")&&(e.localTeam=2));
sa(b);var y=(e.isSpectator?"1":"0")+e.localTeam;if(y!==ba)for(ba=y,y=0;y<v.length;y++){var r=v[y];if(r.ShouldShowToggle){var D=b.FindChildTraverse(r.id);D&&(r.ShouldShowToggle(e)?D.RemoveClass("filterButtonHidden"):D.AddClass("filterButtonHidden"))}}b=g;if(c&&c.IsValid()){var K=(e.isSpectator?"1":"0")+e.localTeam+c.GetChildCount();for(r=0;r<v.length;r++)K+=v[r].active?"1":"0";var E=K;var F=c.GetChildCount()>0?c.GetChild(0):null;if(E!==ca||F!==da)for(ca=E,da=F,b||=c.FindChildrenWithClassTraverse("recentPurchase"),
E=0;E<b.length;E++){var m=b[E];if(m&&m.IsValid()){K=!1;for(F=0;F<v.length;F++){var G=v[F];if((!G.ShouldShowToggle||G.ShouldShowToggle(e))&&(G.invert?!G.active:G.active)&&G.ShouldHideItem(m,e)){K=!0;break}}K?m.AddClass("filterHidden"):m.RemoveClass("filterHidden")}}}ua()&&Y();n!==2&&va();m=g;if(n===2&&c&&c.IsValid())if(m||=c.FindChildrenWithClassTraverse("recentPurchase"),O){for(A=0;A<m.length;A++){var z=m[A];if(z&&z.IsValid()){var H=N(z),ka=W(z);if(H&&ka){var I=H+"|"+ka;w[I]||(w[I]=!0,z.BHasClass("filterHidden")||
za(z,H))}}}z=m;H=0;for(var Aa in w)w.hasOwnProperty(Aa)&&H++;H>300&&ha(c,z)}else{for(var A=0;A<m.length;A++)if((I=m[A])&&I.IsValid()){var la=N(I),ma=W(I);la&&ma&&(w[la+"|"+ma]=!0)}O=!0}S++;S<100||(S=0,ha(c,g))}catch(Ca){}u(.1,ja,a)}}function na(a){if(q&&a===B){try{var b=C(),c=ta(b);if(ea===null||c!==ea)ia(b),u(.5,function(){ia(b)},a);ea=c}catch(d){}u(1,na,a)}}function oa(){C().SetHasClass("recent_purchases_disabled",!q)}function pa(a){a=!!a;if(q===a&&T===a)oa();else if(q=a,B++,T=!1,oa(),q)q&&!T&&
(T=!0,a=B,ja(a),na(a));else{var b=C();a=U(b);var c=b.FindChildTraverse("FiltersCollapseToggle");c&&c.IsValid()&&c.DeleteAsync(0);(b=b.FindChildTraverse("PurchaseFiltersContainer"))&&b.IsValid()&&b.DeleteAsync(0);if(a&&a.IsValid())for(a=a.FindChildrenWithClassTraverse("recentPurchase"),b=0;b<a.length;b++)(c=a[b])&&c.IsValid()&&(c.RemoveClass("filterHidden"),(c=c.FindChildrenWithClassTraverse("mod_icon"))&&c.length!==0&&(c=c[0])&&c.IsValid()&&c.BHasClass("iconSet")&&(c.RemoveClass("iconSet"),c.style.backgroundImage=
"none",c.style.washColor="none"));Y();X=!1;ba=da=ca=null;w={};O=!1;S=0}}function qa(){fa.values.enabled=q;try{$.DispatchEvent("ClientUI_FireOutput",JSON.stringify(fa))}catch(a){}}function Ba(a){if(typeof a==="string"&&a.indexOf('"umm"')!==-1){try{var b=JSON.parse(a)}catch(c){return}b&&b.umm===1&&(b.t==="hello"?qa():b.t==="set"&&b.id===fa.id&&b.key==="enabled"&&typeof b.value==="boolean"&&pa(b.value))}}var fa={umm:1,t:"register",id:"recent_purchases",name:"Recent Purchases",settings:[{id:"enabled",
type:"toggle",label:"Enabled","default":!0,description:"Show and process recent purchases."}],values:{enabled:!0}},v=[{id:"Tier1Toggle",label:"T1",group:"tier",active:!0,invert:!0,ShouldHideItem:function(a){return a.BHasClass("isTier1Purchase")}},{id:"Tier2Toggle",label:"T2",group:"tier",active:!0,invert:!0,ShouldHideItem:function(a){return a.BHasClass("isTier2Purchase")}},{id:"Tier3Toggle",label:"T3",group:"tier",active:!0,invert:!0,ShouldHideItem:function(a){return a.BHasClass("isTier3Purchase")}},
{id:"Tier4Toggle",label:"T4",group:"tier",active:!0,invert:!0,ShouldHideItem:function(a){return a.BHasClass("isTier4Purchase")}},{id:"Team1OnlyToggle",label:"Hidden King",group:"team",active:!0,invert:!0,ShouldShowToggle:function(a){return a.isSpectator},ShouldHideItem:function(a){return a.BHasClass("isTeam1Purchase")}},{id:"Team2OnlyToggle",label:"Archmother",group:"team",active:!0,invert:!0,ShouldShowToggle:function(a){return a.isSpectator},ShouldHideItem:function(a){return a.BHasClass("isTeam2Purchase")}},
{id:"MyTeamToggle",label:"My Team",group:"team",active:!0,invert:!0,ShouldShowToggle:function(a){return!a.isSpectator},ShouldHideItem:function(a,b){return b.localTeam===1?a.BHasClass("isTeam1Purchase"):b.localTeam===2?a.BHasClass("isTeam2Purchase"):!1}},{id:"EnemyTeamToggle",label:"Enemy Team",group:"team",active:!0,invert:!0,ShouldShowToggle:function(a){return!a.isSpectator},ShouldHideItem:function(a,b){return b.localTeam===1?a.BHasClass("isTeam2Purchase"):b.localTeam===2?a.BHasClass("isTeam1Purchase"):
!1}}],aa="isTier1Purchase isTier2Purchase isTier3Purchase isTier4Purchase isWeaponPurchase isArmorPurchase isTechPurchase isTeam1Purchase isTeam2Purchase".split(" "),L=null,M=null,X=!1,ca=null,da=null,ba=null,ea=null,w={},O=!1,J={},n=0,t={},p={},R={},q=!0,B=0,T=!1,P=0,S=0,Q=!1;try{$.RegisterForUnhandledEvent("ClientUI_FireOutput",Ba)}catch(a){}qa();q&&pa(!0)})();
