(function(){function e(a){return a?a.IsValid?a.IsValid():!0:!1}function l(a){if(a===void 0||a===null)return"";a=String(a).replace(/[^0-9]/g,"");return!a||a.length<5||a.length>12?"":a}function p(a,c){if(!e(a)||!c||!a.BHasClass)return!1;try{return!!a.BHasClass(c)}catch(b){return!1}}function x(a){if(!e(a))return!1;a:{var c=0;for(var b=a;e(b)&&c<24;){if(p(b,"isShowingProfilePage")){c=!0;break a}b=b.GetParent?b.GetParent():null;c++}c=!1}if(c)return!0;c=[];c.push(a);for(b=0;b<10&&e(a);b++)a=a.GetParent?
a.GetParent():null,e(a)&&c.push(a);for(a=0;a<c.length;a++)if(b=c[a],p(b,"DashboardPage")&&p(b,"active"))return!0;return!1}function r(a){if(!e(a))return"";var c=[];try{c.push(a.accountid)}catch(d){}try{c.push(a.account_id)}catch(d){}try{c.push(a.accountID)}catch(d){}try{a.GetAttributeString&&(c.push(a.GetAttributeString("accountid","")),c.push(a.GetAttributeString("account_id","")),c.push(a.GetAttributeString("accountID","")))}catch(d){}for(a=0;a<c.length;a++){var b=l(c[a]);if(b)return b}return""}
function y(){try{if(typeof Game!=="undefined"&&Game&&typeof Game.GetLocalPlayerInfo==="function"){var a=Game.GetLocalPlayerInfo();if(a){var c=[a.account_id,a.accountid,a.steamid32];for(a=0;a<c.length;a++){var b=l(c[a]);if(b)return b}}}}catch(z){}try{if(typeof Players!=="undefined"&&Players&&typeof Players.GetLocalPlayer==="function"){var d=Players.GetLocalPlayer();if(d!==void 0&&d!==null){if(typeof Players.GetPlayerData==="function"){var g=Players.GetPlayerData(d);if(g){var f=[g.account_id,g.accountid,
g.steamid32];for(c=0;c<f.length;c++){var h=l(f[c]);if(h)return h}}}if(typeof Players.GetPlayerInfo==="function"){var k=Players.GetPlayerInfo(d);if(k){var m=[k.account_id,k.accountid,k.steamid32];for(d=0;d<m.length;d++){var t=l(m[d]);if(t)return t}}}}}}catch(z){}return""}function q(a,c){a:{if(e(a)&&a.FindChildrenWithClassTraverse){var b=a.FindChildrenWithClassTraverse("AccountID")||[];for(var d=0;d<b.length;d++){var g=b[d];if(e(g)){var f="";try{f=String(g.text||"")}catch(m){f=""}if(g=l(f)){b=g;break a}}}}b=
""}if(b)return{id:b,source:"label:AccountID"};if(b=r(a))return{id:b,source:"ctx_panel"};if(c){a:{if(e(a))for(a=[a],c=0;a.length>0&&c<3E3;)if(b=a.pop(),e(b)){c++;if(d=r(b)){var h=d;break a}try{for(h=b.GetChildCount?b.GetChildCount():0,d=0;d<h;d++){var k=b.GetChild?b.GetChild(d):null;e(k)&&a.push(k)}}catch(m){}}h=""}if(h)return{id:h,source:"panel_tree"}}return(h=y())?{id:h,source:"api_local_player"}:{id:"",source:"-"}}function A(a,c,b){if(e(a)){var d="StatlockerBtn_"+String(b);b=a.FindChildTraverse?
a.FindChildTraverse(d):null;if(!e(b)&&a.FindChildrenWithClassTraverse){var g=a.FindChildrenWithClassTraverse("StatlockerButton")||[];g.length>0&&(b=g[0])}if(!e(b)&&$.CreatePanel){try{b=$.CreatePanel("Button",a,d)}catch(f){b=null}e(b)&&b.AddClass&&b.AddClass("StatlockerButton")}if(e(b)){a=b.FindChildTraverse?b.FindChildTraverse("StatlockerImage"):null;!e(a)&&b.FindChildrenWithClassTraverse&&(d=b.FindChildrenWithClassTraverse("StatlockerImage")||[],d.length>0&&(a=d[0]));if(!e(a)&&$.CreatePanel){try{a=
$.CreatePanel("Image",b,"StatlockerImage")}catch(f){a=null}e(a)&&a.AddClass&&a.AddClass("StatlockerImage")}if(e(a)&&a.SetImage)try{a.SetImage("s2r://panorama/images/statlocker/statlocker.vtex")}catch(f){}b.style.visibility="visible";try{b.enabled=!0}catch(f){}try{b.hittest=!0}catch(f){}try{b.hittestchildren=!0}catch(f){}c&&(u=c);try{b.SetPanelEvent("onactivate",function(){var f=q($.GetContextPanel(),!0);if(f=f&&f.id?f.id:u||c){f="https://statlocker.gg/profile/"+f;try{$.DispatchEvent("ExternalBrowserGoToURL",
f)}catch(h){}try{$.DispatchEvent("SteamOverlayOpenURL",f)}catch(h){}}})}catch(f){}}}}function n(){var a=$.GetContextPanel?$.GetContextPanel():null;if(e(a))if(x(a)){var c=a.FindChildrenWithClassTraverse?a.FindChildrenWithClassTraverse("coreRating")||[]:[];if(c&&!(c.length<=0)){var b=q(a,!1);b=b.id||"";if(!b){var d=Date.now?Date.now():(new Date).getTime();d-v>=1500&&(v=d,b=q(a,!0),b=b.id||"")}a=Date.now?Date.now():(new Date).getTime();a>=w&&(w=a+2E3);for(a=0;a<c.length;a++)d=c[a],e(d)&&d.FindChildTraverse&&
d.FindChildTraverse("HeroRowBackground")&&A(d,b,a)}$.Schedule(.35,n)}else $.Schedule(1,n);else $.Schedule(1,n)}var u="",w=0,v=0;n()})();
